/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6678",
            customMemoryMap:
           [          
                ["L2SRAM", 
                     {
                        name: "L2SRAM",
                        base: 0x00800000,                    
                        len: 0x00080000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["MSMCSRAM", 
                     {
                        name: "MSMCSRAM",
                        base: 0x0c000000,                    
                        len: 0x00400000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["SRIO", 
                     {
                        name: "SRIO",
                        base: 0x80000000,                    
                        len: 0x02800800,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR", 
                     {
                        name: "DDR",
                        base: 0x82800800,                    
                        len: 0x017FD800,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["CORE1DDR", 
                     {
                        name: "CORE1DDR",
                        base: 0x84000000,                    
                        len: 0x04000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l1DMode: "32k",
          l1PMode: "32k",
          l2Mode: "0k",

    });
    
instance :
    
    override config string codeMemory  = "DDR";   
    override config string dataMemory  = "DDR";                                
    override config string stackMemory = "L2SRAM";

    config String l1DMode = "32k";
    config String l1PMode = "32k";
    config String l2Mode = "0k";
}
