#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.elf.C66{1,0,8.3,1
#
app2.xe66: package/cfg/app2.xe66.mak

clean::
	-$(RM) package/cfg/app2.xe66.mak
