/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-E10
 */

#ifndef ti_transport_ipc_c66_qmss_TransportQmss__INTERNAL__
#define ti_transport_ipc_c66_qmss_TransportQmss__INTERNAL__

#ifndef ti_transport_ipc_c66_qmss_TransportQmss__internalaccess
#define ti_transport_ipc_c66_qmss_TransportQmss__internalaccess
#endif

#include <ti/transport/ipc/c66/qmss/TransportQmss.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* bind */
#undef ti_transport_ipc_c66_qmss_TransportQmss_bind
#define ti_transport_ipc_c66_qmss_TransportQmss_bind ti_transport_ipc_c66_qmss_TransportQmss_bind__E

/* unbind */
#undef ti_transport_ipc_c66_qmss_TransportQmss_unbind
#define ti_transport_ipc_c66_qmss_TransportQmss_unbind ti_transport_ipc_c66_qmss_TransportQmss_unbind__E

/* put */
#undef ti_transport_ipc_c66_qmss_TransportQmss_put
#define ti_transport_ipc_c66_qmss_TransportQmss_put ti_transport_ipc_c66_qmss_TransportQmss_put__E

/* recycleUsedTxBufs */
#undef ti_transport_ipc_c66_qmss_TransportQmss_recycleUsedTxBufs
#define ti_transport_ipc_c66_qmss_TransportQmss_recycleUsedTxBufs ti_transport_ipc_c66_qmss_TransportQmss_recycleUsedTxBufs__E

/* flushDstCache */
#undef ti_transport_ipc_c66_qmss_TransportQmss_flushDstCache
#define ti_transport_ipc_c66_qmss_TransportQmss_flushDstCache ti_transport_ipc_c66_qmss_TransportQmss_flushDstCache__E

/* Accum_isr */
#define TransportQmss_Accum_isr ti_transport_ipc_c66_qmss_TransportQmss_Accum_isr__I

/* Qpend_isr */
#define TransportQmss_Qpend_isr ti_transport_ipc_c66_qmss_TransportQmss_Qpend_isr__I

/* Module_startup */
#undef ti_transport_ipc_c66_qmss_TransportQmss_Module_startup
#define ti_transport_ipc_c66_qmss_TransportQmss_Module_startup ti_transport_ipc_c66_qmss_TransportQmss_Module_startup__E

/* Instance_init */
#undef ti_transport_ipc_c66_qmss_TransportQmss_Instance_init
#define ti_transport_ipc_c66_qmss_TransportQmss_Instance_init ti_transport_ipc_c66_qmss_TransportQmss_Instance_init__E

/* Instance_finalize */
#undef ti_transport_ipc_c66_qmss_TransportQmss_Instance_finalize
#define ti_transport_ipc_c66_qmss_TransportQmss_Instance_finalize ti_transport_ipc_c66_qmss_TransportQmss_Instance_finalize__E

/* module */
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__state__VR
#define TransportQmss_module ((ti_transport_ipc_c66_qmss_TransportQmss_Module_State *)(xdcRomStatePtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__state__V_offset))
#define module ((ti_transport_ipc_c66_qmss_TransportQmss_Module_State *)(xdcRomStatePtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__state__V_offset))
#else
#define TransportQmss_module ((ti_transport_ipc_c66_qmss_TransportQmss_Module_State *)(xdc__MODOBJADDR__(ti_transport_ipc_c66_qmss_TransportQmss_Module__state__V)))
#if !defined(__cplusplus) ||!defined(ti_transport_ipc_c66_qmss_TransportQmss__cplusplus)
#define module ((ti_transport_ipc_c66_qmss_TransportQmss_Module_State *)(xdc__MODOBJADDR__(ti_transport_ipc_c66_qmss_TransportQmss_Module__state__V)))
#endif
#endif

/* per-module runtime symbols */
#undef Module__MID
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__id__CR
#define Module__MID (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__id *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__id__C_offset)))
#else
#define Module__MID ti_transport_ipc_c66_qmss_TransportQmss_Module__id__C
#endif

#undef Module__DGSINCL
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsIncluded__CR
#define Module__DGSINCL (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsIncluded *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsIncluded__C_offset)))
#else
#define Module__DGSINCL ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsIncluded__C
#endif

#undef Module__DGSENAB
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsEnabled__CR
#define Module__DGSENAB (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsEnabled *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsEnabled__C_offset)))
#else
#define Module__DGSENAB ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsEnabled__C
#endif

#undef Module__DGSMASK
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsMask__CR
#define Module__DGSMASK (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsMask *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsMask__C_offset)))
#else
#define Module__DGSMASK ti_transport_ipc_c66_qmss_TransportQmss_Module__diagsMask__C
#endif

#undef Module__LOGDEF
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerDefined__CR
#define Module__LOGDEF (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerDefined *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerDefined__C_offset)))
#else
#define Module__LOGDEF ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerDefined__C
#endif

#undef Module__LOGOBJ
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerObj__CR
#define Module__LOGOBJ ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerObj__R
#define Module__LOGOBJ (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerObj *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerObj__C_offset)))
#else
#define Module__LOGOBJ ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerObj__C
#endif

#undef Module__LOGFXN0
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn0__CR
#define Module__LOGFXN0 (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn0 *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn0__C_offset)))
#else
#define Module__LOGFXN0 ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn0__C
#endif

#undef Module__LOGFXN1
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn1__CR
#define Module__LOGFXN1 (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn1 *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn1__C_offset)))
#else
#define Module__LOGFXN1 ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn1__C
#endif

#undef Module__LOGFXN2
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn2__CR
#define Module__LOGFXN2 (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn2 *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn2__C_offset)))
#else
#define Module__LOGFXN2 ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn2__C
#endif

#undef Module__LOGFXN4
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn4__CR
#define Module__LOGFXN4 (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn4 *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn4__C_offset)))
#else
#define Module__LOGFXN4 ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn4__C
#endif

#undef Module__LOGFXN8
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn8__CR
#define Module__LOGFXN8 (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn8 *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn8__C_offset)))
#else
#define Module__LOGFXN8 ti_transport_ipc_c66_qmss_TransportQmss_Module__loggerFxn8__C
#endif

#undef Module__G_OBJ
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__gateObj__CR
#define Module__G_OBJ (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__gateObj *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__gateObj__C_offset)))
#else
#define Module__G_OBJ ti_transport_ipc_c66_qmss_TransportQmss_Module__gateObj__C
#endif

#undef Module__G_PRMS
#ifdef ti_transport_ipc_c66_qmss_TransportQmss_Module__gatePrms__CR
#define Module__G_PRMS (*((CT__ti_transport_ipc_c66_qmss_TransportQmss_Module__gatePrms *)(xdcRomConstPtr + ti_transport_ipc_c66_qmss_TransportQmss_Module__gatePrms__C_offset)))
#else
#define Module__G_PRMS ti_transport_ipc_c66_qmss_TransportQmss_Module__gatePrms__C
#endif

#undef Module__GP_create
#define Module__GP_create ti_transport_ipc_c66_qmss_TransportQmss_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_transport_ipc_c66_qmss_TransportQmss_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_transport_ipc_c66_qmss_TransportQmss_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_transport_ipc_c66_qmss_TransportQmss_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_transport_ipc_c66_qmss_TransportQmss_Module_GateProxy_query

/* Object__sizingError */
#line 1 "Error_inconsistent_object_size_in_ti.transport.ipc.c66.qmss.TransportQmss"
typedef char ti_transport_ipc_c66_qmss_TransportQmss_Object__sizingError[(sizeof(ti_transport_ipc_c66_qmss_TransportQmss_Object) > sizeof(ti_transport_ipc_c66_qmss_TransportQmss_Struct)) ? -1 : 1];


#endif /* ti_transport_ipc_c66_qmss_TransportQmss__INTERNAL____ */
