/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types -fskeletons-copy`
 */

#include "RF-ParametersMRDC.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_srs_SwitchingTimeRequested_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_srs_SwitchingTimeRequested_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_srs_SwitchingTimeRequested_value2enum_5[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_srs_SwitchingTimeRequested_enum2value_5[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_srs_SwitchingTimeRequested_specs_5 = {
	asn_MAP_srs_SwitchingTimeRequested_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_srs_SwitchingTimeRequested_enum2value_5,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_srs_SwitchingTimeRequested_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_srs_SwitchingTimeRequested_5 = {
	"srs-SwitchingTimeRequested",
	"srs-SwitchingTimeRequested",
	&asn_OP_NativeEnumerated,
	asn_DEF_srs_SwitchingTimeRequested_tags_5,
	sizeof(asn_DEF_srs_SwitchingTimeRequested_tags_5)
		/sizeof(asn_DEF_srs_SwitchingTimeRequested_tags_5[0]) - 1, /* 1 */
	asn_DEF_srs_SwitchingTimeRequested_tags_5,	/* Same as above */
	sizeof(asn_DEF_srs_SwitchingTimeRequested_tags_5)
		/sizeof(asn_DEF_srs_SwitchingTimeRequested_tags_5[0]), /* 2 */
	{ &asn_OER_type_srs_SwitchingTimeRequested_constr_5, &asn_PER_type_srs_SwitchingTimeRequested_constr_5, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_srs_SwitchingTimeRequested_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RF_ParametersMRDC_1[] = {
	{ ATF_POINTER, 7, offsetof(struct RF_ParametersMRDC, supportedBandCombinationList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BandCombinationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList"
		},
	{ ATF_POINTER, 6, offsetof(struct RF_ParametersMRDC, appliedFreqBandListFilter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreqBandList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"appliedFreqBandListFilter"
		},
	{ ATF_POINTER, 5, offsetof(struct RF_ParametersMRDC, srs_SwitchingTimeRequested),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_srs_SwitchingTimeRequested_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srs-SwitchingTimeRequested"
		},
	{ ATF_POINTER, 4, offsetof(struct RF_ParametersMRDC, supportedBandCombinationList_v1540),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BandCombinationList_v1540,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1540"
		},
	{ ATF_POINTER, 3, offsetof(struct RF_ParametersMRDC, supportedBandCombinationList_v1550),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BandCombinationList_v1550,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1550"
		},
	{ ATF_POINTER, 2, offsetof(struct RF_ParametersMRDC, supportedBandCombinationList_v1560),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BandCombinationList_v1560,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1560"
		},
	{ ATF_POINTER, 1, offsetof(struct RF_ParametersMRDC, supportedBandCombinationListNEDC_Only),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BandCombinationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only"
		},
};
static const int asn_MAP_RF_ParametersMRDC_oms_1[] = { 0, 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_RF_ParametersMRDC_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RF_ParametersMRDC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedBandCombinationList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* appliedFreqBandListFilter */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* srs-SwitchingTimeRequested */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* supportedBandCombinationList-v1540 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* supportedBandCombinationList-v1550 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* supportedBandCombinationList-v1560 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* supportedBandCombinationListNEDC-Only */
};
asn_SEQUENCE_specifics_t asn_SPC_RF_ParametersMRDC_specs_1 = {
	sizeof(struct RF_ParametersMRDC),
	offsetof(struct RF_ParametersMRDC, _asn_ctx),
	asn_MAP_RF_ParametersMRDC_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_RF_ParametersMRDC_oms_1,	/* Optional members */
	2, 5,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RF_ParametersMRDC = {
	"RF-ParametersMRDC",
	"RF-ParametersMRDC",
	&asn_OP_SEQUENCE,
	asn_DEF_RF_ParametersMRDC_tags_1,
	sizeof(asn_DEF_RF_ParametersMRDC_tags_1)
		/sizeof(asn_DEF_RF_ParametersMRDC_tags_1[0]), /* 1 */
	asn_DEF_RF_ParametersMRDC_tags_1,	/* Same as above */
	sizeof(asn_DEF_RF_ParametersMRDC_tags_1)
		/sizeof(asn_DEF_RF_ParametersMRDC_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RF_ParametersMRDC_1,
	7,	/* Elements count */
	&asn_SPC_RF_ParametersMRDC_specs_1	/* Additional specs */
};

