/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "38331-f60.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types -fskeletons-copy`
 */

#ifndef	_SetupRelease_H_
#define	_SetupRelease_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "LocationMeasurementInfo.h"
#include "constr_CHOICE.h"
#include "MRDC-SecondaryCellGroupConfig.h"
#include "PDCCH-ConfigCommon.h"
#include "PDSCH-ConfigCommon.h"
#include "PDCCH-Config.h"
#include "PDSCH-Config.h"
#include "SPS-Config.h"
#include "RadioLinkMonitoringConfig.h"
#include "RACH-ConfigCommon.h"
#include "PUSCH-ConfigCommon.h"
#include "PUCCH-ConfigCommon.h"
#include "PUCCH-Config.h"
#include "PUSCH-Config.h"
#include "ConfiguredGrantConfig.h"
#include "SRS-Config.h"
#include "BeamFailureRecoveryConfig.h"
#include "RLF-TimersAndConstants.h"
#include "CG-UCI-OnPUSCH.h"
#include "CSI-AperiodicTriggerStateList.h"
#include "CSI-SemiPersistentOnPUSCH-TriggerStateList.h"
#include "PTRS-DownlinkConfig.h"
#include "PTRS-UplinkConfig.h"
#include "DRX-Config.h"
#include "PHR-Config.h"
#include "DataInactivityTimer.h"
#include "GapConfig.h"
#include "MeasGapSharingScheme.h"
#include "CSI-RS-ResourceConfigMobility.h"
#include "SSB-ToMeasure.h"
#include "DownlinkPreemption.h"
#include "PUSCH-TPC-CommandConfig.h"
#include "PUCCH-TPC-CommandConfig.h"
#include "SRS-TPC-CommandConfig.h"
#include "SlotFormatIndicator.h"
#include "DMRS-DownlinkConfig.h"
#include "PDSCH-TimeDomainResourceAllocationList.h"
#include "ZP-CSI-RS-ResourceSet.h"
#include "PDSCH-CodeBlockGroupTransmission.h"
#include "RNTI-Value.h"
#include "PDCCH-BlindDetection.h"
#include "PUCCH-FormatConfig.h"
#include "DMRS-UplinkConfig.h"
#include "PUSCH-TimeDomainResourceAllocationList.h"
#include "UCI-OnPUSCH.h"
#include "PUSCH-CodeBlockGroupTransmission.h"
#include "PDCCH-ServingCellConfig.h"
#include "PDSCH-ServingCellConfig.h"
#include "CSI-MeasConfig.h"
#include "RateMatchPatternLTE-CRS.h"
#include "PUSCH-ServingCellConfig.h"
#include "SRS-CarrierSwitching.h"
#include "OverheatingAssistanceConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SetupRelease_1076P0_PR {
	SetupRelease_1076P0_PR_NOTHING,	/* No components present */
	SetupRelease_1076P0_PR_release,
	SetupRelease_1076P0_PR_setup
} SetupRelease_1076P0_PR;
typedef enum SetupRelease_1076P1_PR {
	SetupRelease_1076P1_PR_NOTHING,	/* No components present */
	SetupRelease_1076P1_PR_release,
	SetupRelease_1076P1_PR_setup
} SetupRelease_1076P1_PR;
typedef enum SetupRelease_1076P2_PR {
	SetupRelease_1076P2_PR_NOTHING,	/* No components present */
	SetupRelease_1076P2_PR_release,
	SetupRelease_1076P2_PR_setup
} SetupRelease_1076P2_PR;
typedef enum SetupRelease_1076P3_PR {
	SetupRelease_1076P3_PR_NOTHING,	/* No components present */
	SetupRelease_1076P3_PR_release,
	SetupRelease_1076P3_PR_setup
} SetupRelease_1076P3_PR;
typedef enum SetupRelease_1076P4_PR {
	SetupRelease_1076P4_PR_NOTHING,	/* No components present */
	SetupRelease_1076P4_PR_release,
	SetupRelease_1076P4_PR_setup
} SetupRelease_1076P4_PR;
typedef enum SetupRelease_1076P5_PR {
	SetupRelease_1076P5_PR_NOTHING,	/* No components present */
	SetupRelease_1076P5_PR_release,
	SetupRelease_1076P5_PR_setup
} SetupRelease_1076P5_PR;
typedef enum SetupRelease_1076P6_PR {
	SetupRelease_1076P6_PR_NOTHING,	/* No components present */
	SetupRelease_1076P6_PR_release,
	SetupRelease_1076P6_PR_setup
} SetupRelease_1076P6_PR;
typedef enum SetupRelease_1076P7_PR {
	SetupRelease_1076P7_PR_NOTHING,	/* No components present */
	SetupRelease_1076P7_PR_release,
	SetupRelease_1076P7_PR_setup
} SetupRelease_1076P7_PR;
typedef enum SetupRelease_1076P8_PR {
	SetupRelease_1076P8_PR_NOTHING,	/* No components present */
	SetupRelease_1076P8_PR_release,
	SetupRelease_1076P8_PR_setup
} SetupRelease_1076P8_PR;
typedef enum SetupRelease_1076P9_PR {
	SetupRelease_1076P9_PR_NOTHING,	/* No components present */
	SetupRelease_1076P9_PR_release,
	SetupRelease_1076P9_PR_setup
} SetupRelease_1076P9_PR;
typedef enum SetupRelease_1076P10_PR {
	SetupRelease_1076P10_PR_NOTHING,	/* No components present */
	SetupRelease_1076P10_PR_release,
	SetupRelease_1076P10_PR_setup
} SetupRelease_1076P10_PR;
typedef enum SetupRelease_1076P11_PR {
	SetupRelease_1076P11_PR_NOTHING,	/* No components present */
	SetupRelease_1076P11_PR_release,
	SetupRelease_1076P11_PR_setup
} SetupRelease_1076P11_PR;
typedef enum SetupRelease_1076P12_PR {
	SetupRelease_1076P12_PR_NOTHING,	/* No components present */
	SetupRelease_1076P12_PR_release,
	SetupRelease_1076P12_PR_setup
} SetupRelease_1076P12_PR;
typedef enum SetupRelease_1076P13_PR {
	SetupRelease_1076P13_PR_NOTHING,	/* No components present */
	SetupRelease_1076P13_PR_release,
	SetupRelease_1076P13_PR_setup
} SetupRelease_1076P13_PR;
typedef enum SetupRelease_1076P14_PR {
	SetupRelease_1076P14_PR_NOTHING,	/* No components present */
	SetupRelease_1076P14_PR_release,
	SetupRelease_1076P14_PR_setup
} SetupRelease_1076P14_PR;
typedef enum SetupRelease_1076P15_PR {
	SetupRelease_1076P15_PR_NOTHING,	/* No components present */
	SetupRelease_1076P15_PR_release,
	SetupRelease_1076P15_PR_setup
} SetupRelease_1076P15_PR;
typedef enum SetupRelease_1076P16_PR {
	SetupRelease_1076P16_PR_NOTHING,	/* No components present */
	SetupRelease_1076P16_PR_release,
	SetupRelease_1076P16_PR_setup
} SetupRelease_1076P16_PR;
typedef enum SetupRelease_1076P17_PR {
	SetupRelease_1076P17_PR_NOTHING,	/* No components present */
	SetupRelease_1076P17_PR_release,
	SetupRelease_1076P17_PR_setup
} SetupRelease_1076P17_PR;
typedef enum SetupRelease_1076P18_PR {
	SetupRelease_1076P18_PR_NOTHING,	/* No components present */
	SetupRelease_1076P18_PR_release,
	SetupRelease_1076P18_PR_setup
} SetupRelease_1076P18_PR;
typedef enum SetupRelease_1076P19_PR {
	SetupRelease_1076P19_PR_NOTHING,	/* No components present */
	SetupRelease_1076P19_PR_release,
	SetupRelease_1076P19_PR_setup
} SetupRelease_1076P19_PR;
typedef enum SetupRelease_1076P20_PR {
	SetupRelease_1076P20_PR_NOTHING,	/* No components present */
	SetupRelease_1076P20_PR_release,
	SetupRelease_1076P20_PR_setup
} SetupRelease_1076P20_PR;
typedef enum SetupRelease_1076P21_PR {
	SetupRelease_1076P21_PR_NOTHING,	/* No components present */
	SetupRelease_1076P21_PR_release,
	SetupRelease_1076P21_PR_setup
} SetupRelease_1076P21_PR;
typedef enum SetupRelease_1076P22_PR {
	SetupRelease_1076P22_PR_NOTHING,	/* No components present */
	SetupRelease_1076P22_PR_release,
	SetupRelease_1076P22_PR_setup
} SetupRelease_1076P22_PR;
typedef enum SetupRelease_1076P23_PR {
	SetupRelease_1076P23_PR_NOTHING,	/* No components present */
	SetupRelease_1076P23_PR_release,
	SetupRelease_1076P23_PR_setup
} SetupRelease_1076P23_PR;
typedef enum SetupRelease_1076P24_PR {
	SetupRelease_1076P24_PR_NOTHING,	/* No components present */
	SetupRelease_1076P24_PR_release,
	SetupRelease_1076P24_PR_setup
} SetupRelease_1076P24_PR;
typedef enum SetupRelease_1076P25_PR {
	SetupRelease_1076P25_PR_NOTHING,	/* No components present */
	SetupRelease_1076P25_PR_release,
	SetupRelease_1076P25_PR_setup
} SetupRelease_1076P25_PR;
typedef enum SetupRelease_1076P26_PR {
	SetupRelease_1076P26_PR_NOTHING,	/* No components present */
	SetupRelease_1076P26_PR_release,
	SetupRelease_1076P26_PR_setup
} SetupRelease_1076P26_PR;
typedef enum SetupRelease_1076P27_PR {
	SetupRelease_1076P27_PR_NOTHING,	/* No components present */
	SetupRelease_1076P27_PR_release,
	SetupRelease_1076P27_PR_setup
} SetupRelease_1076P27_PR;
typedef enum SetupRelease_1076P28_PR {
	SetupRelease_1076P28_PR_NOTHING,	/* No components present */
	SetupRelease_1076P28_PR_release,
	SetupRelease_1076P28_PR_setup
} SetupRelease_1076P28_PR;
typedef enum SetupRelease_1076P29_PR {
	SetupRelease_1076P29_PR_NOTHING,	/* No components present */
	SetupRelease_1076P29_PR_release,
	SetupRelease_1076P29_PR_setup
} SetupRelease_1076P29_PR;
typedef enum SetupRelease_1076P30_PR {
	SetupRelease_1076P30_PR_NOTHING,	/* No components present */
	SetupRelease_1076P30_PR_release,
	SetupRelease_1076P30_PR_setup
} SetupRelease_1076P30_PR;
typedef enum SetupRelease_1076P31_PR {
	SetupRelease_1076P31_PR_NOTHING,	/* No components present */
	SetupRelease_1076P31_PR_release,
	SetupRelease_1076P31_PR_setup
} SetupRelease_1076P31_PR;
typedef enum SetupRelease_1076P32_PR {
	SetupRelease_1076P32_PR_NOTHING,	/* No components present */
	SetupRelease_1076P32_PR_release,
	SetupRelease_1076P32_PR_setup
} SetupRelease_1076P32_PR;
typedef enum SetupRelease_1076P33_PR {
	SetupRelease_1076P33_PR_NOTHING,	/* No components present */
	SetupRelease_1076P33_PR_release,
	SetupRelease_1076P33_PR_setup
} SetupRelease_1076P33_PR;
typedef enum SetupRelease_1076P34_PR {
	SetupRelease_1076P34_PR_NOTHING,	/* No components present */
	SetupRelease_1076P34_PR_release,
	SetupRelease_1076P34_PR_setup
} SetupRelease_1076P34_PR;
typedef enum SetupRelease_1076P35_PR {
	SetupRelease_1076P35_PR_NOTHING,	/* No components present */
	SetupRelease_1076P35_PR_release,
	SetupRelease_1076P35_PR_setup
} SetupRelease_1076P35_PR;
typedef enum SetupRelease_1076P36_PR {
	SetupRelease_1076P36_PR_NOTHING,	/* No components present */
	SetupRelease_1076P36_PR_release,
	SetupRelease_1076P36_PR_setup
} SetupRelease_1076P36_PR;
typedef enum SetupRelease_1076P37_PR {
	SetupRelease_1076P37_PR_NOTHING,	/* No components present */
	SetupRelease_1076P37_PR_release,
	SetupRelease_1076P37_PR_setup
} SetupRelease_1076P37_PR;
typedef enum SetupRelease_1076P38_PR {
	SetupRelease_1076P38_PR_NOTHING,	/* No components present */
	SetupRelease_1076P38_PR_release,
	SetupRelease_1076P38_PR_setup
} SetupRelease_1076P38_PR;
typedef enum SetupRelease_1076P39_PR {
	SetupRelease_1076P39_PR_NOTHING,	/* No components present */
	SetupRelease_1076P39_PR_release,
	SetupRelease_1076P39_PR_setup
} SetupRelease_1076P39_PR;
typedef enum SetupRelease_1076P40_PR {
	SetupRelease_1076P40_PR_NOTHING,	/* No components present */
	SetupRelease_1076P40_PR_release,
	SetupRelease_1076P40_PR_setup
} SetupRelease_1076P40_PR;
typedef enum SetupRelease_1076P41_PR {
	SetupRelease_1076P41_PR_NOTHING,	/* No components present */
	SetupRelease_1076P41_PR_release,
	SetupRelease_1076P41_PR_setup
} SetupRelease_1076P41_PR;
typedef enum SetupRelease_1076P42_PR {
	SetupRelease_1076P42_PR_NOTHING,	/* No components present */
	SetupRelease_1076P42_PR_release,
	SetupRelease_1076P42_PR_setup
} SetupRelease_1076P42_PR;
typedef enum SetupRelease_1076P43_PR {
	SetupRelease_1076P43_PR_NOTHING,	/* No components present */
	SetupRelease_1076P43_PR_release,
	SetupRelease_1076P43_PR_setup
} SetupRelease_1076P43_PR;
typedef enum SetupRelease_1076P44_PR {
	SetupRelease_1076P44_PR_NOTHING,	/* No components present */
	SetupRelease_1076P44_PR_release,
	SetupRelease_1076P44_PR_setup
} SetupRelease_1076P44_PR;
typedef enum SetupRelease_1076P45_PR {
	SetupRelease_1076P45_PR_NOTHING,	/* No components present */
	SetupRelease_1076P45_PR_release,
	SetupRelease_1076P45_PR_setup
} SetupRelease_1076P45_PR;
typedef enum SetupRelease_1076P46_PR {
	SetupRelease_1076P46_PR_NOTHING,	/* No components present */
	SetupRelease_1076P46_PR_release,
	SetupRelease_1076P46_PR_setup
} SetupRelease_1076P46_PR;
typedef enum SetupRelease_1076P47_PR {
	SetupRelease_1076P47_PR_NOTHING,	/* No components present */
	SetupRelease_1076P47_PR_release,
	SetupRelease_1076P47_PR_setup
} SetupRelease_1076P47_PR;
typedef enum SetupRelease_1076P48_PR {
	SetupRelease_1076P48_PR_NOTHING,	/* No components present */
	SetupRelease_1076P48_PR_release,
	SetupRelease_1076P48_PR_setup
} SetupRelease_1076P48_PR;
typedef enum SetupRelease_1076P49_PR {
	SetupRelease_1076P49_PR_NOTHING,	/* No components present */
	SetupRelease_1076P49_PR_release,
	SetupRelease_1076P49_PR_setup
} SetupRelease_1076P49_PR;
typedef enum SetupRelease_1076P50_PR {
	SetupRelease_1076P50_PR_NOTHING,	/* No components present */
	SetupRelease_1076P50_PR_release,
	SetupRelease_1076P50_PR_setup
} SetupRelease_1076P50_PR;
typedef enum SetupRelease_1076P51_PR {
	SetupRelease_1076P51_PR_NOTHING,	/* No components present */
	SetupRelease_1076P51_PR_release,
	SetupRelease_1076P51_PR_setup
} SetupRelease_1076P51_PR;
typedef enum SetupRelease_1076P52_PR {
	SetupRelease_1076P52_PR_NOTHING,	/* No components present */
	SetupRelease_1076P52_PR_release,
	SetupRelease_1076P52_PR_setup
} SetupRelease_1076P52_PR;

/* SetupRelease */
typedef struct SetupRelease_1076P0 {
	SetupRelease_1076P0_PR present;
	union SetupRelease_1076P0_u {
		NULL_t	 release;
		LocationMeasurementInfo_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P0_t;
typedef struct SetupRelease_1076P1 {
	SetupRelease_1076P1_PR present;
	union SetupRelease_1076P1_u {
		NULL_t	 release;
		MRDC_SecondaryCellGroupConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P1_t;
typedef struct SetupRelease_1076P2 {
	SetupRelease_1076P2_PR present;
	union SetupRelease_1076P2_u {
		NULL_t	 release;
		PDCCH_ConfigCommon_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P2_t;
typedef struct SetupRelease_1076P3 {
	SetupRelease_1076P3_PR present;
	union SetupRelease_1076P3_u {
		NULL_t	 release;
		PDSCH_ConfigCommon_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P3_t;
typedef struct SetupRelease_1076P4 {
	SetupRelease_1076P4_PR present;
	union SetupRelease_1076P4_u {
		NULL_t	 release;
		PDCCH_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P4_t;
typedef struct SetupRelease_1076P5 {
	SetupRelease_1076P5_PR present;
	union SetupRelease_1076P5_u {
		NULL_t	 release;
		PDSCH_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P5_t;
typedef struct SetupRelease_1076P6 {
	SetupRelease_1076P6_PR present;
	union SetupRelease_1076P6_u {
		NULL_t	 release;
		SPS_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P6_t;
typedef struct SetupRelease_1076P7 {
	SetupRelease_1076P7_PR present;
	union SetupRelease_1076P7_u {
		NULL_t	 release;
		RadioLinkMonitoringConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P7_t;
typedef struct SetupRelease_1076P8 {
	SetupRelease_1076P8_PR present;
	union SetupRelease_1076P8_u {
		NULL_t	 release;
		RACH_ConfigCommon_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P8_t;
typedef struct SetupRelease_1076P9 {
	SetupRelease_1076P9_PR present;
	union SetupRelease_1076P9_u {
		NULL_t	 release;
		PUSCH_ConfigCommon_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P9_t;
typedef struct SetupRelease_1076P10 {
	SetupRelease_1076P10_PR present;
	union SetupRelease_1076P10_u {
		NULL_t	 release;
		PUCCH_ConfigCommon_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P10_t;
typedef struct SetupRelease_1076P11 {
	SetupRelease_1076P11_PR present;
	union SetupRelease_1076P11_u {
		NULL_t	 release;
		PUCCH_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P11_t;
typedef struct SetupRelease_1076P12 {
	SetupRelease_1076P12_PR present;
	union SetupRelease_1076P12_u {
		NULL_t	 release;
		PUSCH_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P12_t;
typedef struct SetupRelease_1076P13 {
	SetupRelease_1076P13_PR present;
	union SetupRelease_1076P13_u {
		NULL_t	 release;
		ConfiguredGrantConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P13_t;
typedef struct SetupRelease_1076P14 {
	SetupRelease_1076P14_PR present;
	union SetupRelease_1076P14_u {
		NULL_t	 release;
		SRS_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P14_t;
typedef struct SetupRelease_1076P15 {
	SetupRelease_1076P15_PR present;
	union SetupRelease_1076P15_u {
		NULL_t	 release;
		BeamFailureRecoveryConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P15_t;
typedef struct SetupRelease_1076P16 {
	SetupRelease_1076P16_PR present;
	union SetupRelease_1076P16_u {
		NULL_t	 release;
		RLF_TimersAndConstants_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P16_t;
typedef struct SetupRelease_1076P17 {
	SetupRelease_1076P17_PR present;
	union SetupRelease_1076P17_u {
		NULL_t	 release;
		CG_UCI_OnPUSCH_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P17_t;
typedef struct SetupRelease_1076P18 {
	SetupRelease_1076P18_PR present;
	union SetupRelease_1076P18_u {
		NULL_t	 release;
		CSI_AperiodicTriggerStateList_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P18_t;
typedef struct SetupRelease_1076P19 {
	SetupRelease_1076P19_PR present;
	union SetupRelease_1076P19_u {
		NULL_t	 release;
		CSI_SemiPersistentOnPUSCH_TriggerStateList_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P19_t;
typedef struct SetupRelease_1076P20 {
	SetupRelease_1076P20_PR present;
	union SetupRelease_1076P20_u {
		NULL_t	 release;
		PTRS_DownlinkConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P20_t;
typedef struct SetupRelease_1076P21 {
	SetupRelease_1076P21_PR present;
	union SetupRelease_1076P21_u {
		NULL_t	 release;
		PTRS_UplinkConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P21_t;
typedef struct SetupRelease_1076P22 {
	SetupRelease_1076P22_PR present;
	union SetupRelease_1076P22_u {
		NULL_t	 release;
		DRX_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P22_t;
typedef struct SetupRelease_1076P23 {
	SetupRelease_1076P23_PR present;
	union SetupRelease_1076P23_u {
		NULL_t	 release;
		PHR_Config_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P23_t;
typedef struct SetupRelease_1076P24 {
	SetupRelease_1076P24_PR present;
	union SetupRelease_1076P24_u {
		NULL_t	 release;
		DataInactivityTimer_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P24_t;
typedef struct SetupRelease_1076P25 {
	SetupRelease_1076P25_PR present;
	union SetupRelease_1076P25_u {
		NULL_t	 release;
		GapConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P25_t;
typedef struct SetupRelease_1076P26 {
	SetupRelease_1076P26_PR present;
	union SetupRelease_1076P26_u {
		NULL_t	 release;
		MeasGapSharingScheme_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P26_t;
typedef struct SetupRelease_1076P27 {
	SetupRelease_1076P27_PR present;
	union SetupRelease_1076P27_u {
		NULL_t	 release;
		CSI_RS_ResourceConfigMobility_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P27_t;
typedef struct SetupRelease_1076P28 {
	SetupRelease_1076P28_PR present;
	union SetupRelease_1076P28_u {
		NULL_t	 release;
		SSB_ToMeasure_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P28_t;
typedef struct SetupRelease_1076P29 {
	SetupRelease_1076P29_PR present;
	union SetupRelease_1076P29_u {
		NULL_t	 release;
		DownlinkPreemption_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P29_t;
typedef struct SetupRelease_1076P30 {
	SetupRelease_1076P30_PR present;
	union SetupRelease_1076P30_u {
		NULL_t	 release;
		PUSCH_TPC_CommandConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P30_t;
typedef struct SetupRelease_1076P31 {
	SetupRelease_1076P31_PR present;
	union SetupRelease_1076P31_u {
		NULL_t	 release;
		PUCCH_TPC_CommandConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P31_t;
typedef struct SetupRelease_1076P32 {
	SetupRelease_1076P32_PR present;
	union SetupRelease_1076P32_u {
		NULL_t	 release;
		SRS_TPC_CommandConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P32_t;
typedef struct SetupRelease_1076P33 {
	SetupRelease_1076P33_PR present;
	union SetupRelease_1076P33_u {
		NULL_t	 release;
		SlotFormatIndicator_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P33_t;
typedef struct SetupRelease_1076P34 {
	SetupRelease_1076P34_PR present;
	union SetupRelease_1076P34_u {
		NULL_t	 release;
		DMRS_DownlinkConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P34_t;
typedef struct SetupRelease_1076P35 {
	SetupRelease_1076P35_PR present;
	union SetupRelease_1076P35_u {
		NULL_t	 release;
		PDSCH_TimeDomainResourceAllocationList_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P35_t;
typedef struct SetupRelease_1076P36 {
	SetupRelease_1076P36_PR present;
	union SetupRelease_1076P36_u {
		NULL_t	 release;
		ZP_CSI_RS_ResourceSet_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P36_t;
typedef struct SetupRelease_1076P37 {
	SetupRelease_1076P37_PR present;
	union SetupRelease_1076P37_u {
		NULL_t	 release;
		PDSCH_CodeBlockGroupTransmission_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P37_t;
typedef struct SetupRelease_1076P38 {
	SetupRelease_1076P38_PR present;
	union SetupRelease_1076P38_u {
		NULL_t	 release;
		RNTI_Value_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P38_t;
typedef struct SetupRelease_1076P39 {
	SetupRelease_1076P39_PR present;
	union SetupRelease_1076P39_u {
		NULL_t	 release;
		PDCCH_BlindDetection_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P39_t;
typedef struct SetupRelease_1076P40 {
	SetupRelease_1076P40_PR present;
	union SetupRelease_1076P40_u {
		NULL_t	 release;
		PUCCH_FormatConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P40_t;
typedef struct SetupRelease_1076P41 {
	SetupRelease_1076P41_PR present;
	union SetupRelease_1076P41_u {
		NULL_t	 release;
		DMRS_UplinkConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P41_t;
typedef struct SetupRelease_1076P42 {
	SetupRelease_1076P42_PR present;
	union SetupRelease_1076P42_u {
		NULL_t	 release;
		PUSCH_TimeDomainResourceAllocationList_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P42_t;
typedef struct SetupRelease_1076P43 {
	SetupRelease_1076P43_PR present;
	union SetupRelease_1076P43_u {
		NULL_t	 release;
		UCI_OnPUSCH_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P43_t;
typedef struct SetupRelease_1076P44 {
	SetupRelease_1076P44_PR present;
	union SetupRelease_1076P44_u {
		NULL_t	 release;
		PUSCH_CodeBlockGroupTransmission_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P44_t;
typedef struct SetupRelease_1076P45 {
	SetupRelease_1076P45_PR present;
	union SetupRelease_1076P45_u {
		NULL_t	 release;
		PDCCH_ServingCellConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P45_t;
typedef struct SetupRelease_1076P46 {
	SetupRelease_1076P46_PR present;
	union SetupRelease_1076P46_u {
		NULL_t	 release;
		PDSCH_ServingCellConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P46_t;
typedef struct SetupRelease_1076P47 {
	SetupRelease_1076P47_PR present;
	union SetupRelease_1076P47_u {
		NULL_t	 release;
		CSI_MeasConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P47_t;
typedef struct SetupRelease_1076P48 {
	SetupRelease_1076P48_PR present;
	union SetupRelease_1076P48_u {
		NULL_t	 release;
		RateMatchPatternLTE_CRS_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P48_t;
typedef struct SetupRelease_1076P49 {
	SetupRelease_1076P49_PR present;
	union SetupRelease_1076P49_u {
		NULL_t	 release;
		PUSCH_ServingCellConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P49_t;
typedef struct SetupRelease_1076P50 {
	SetupRelease_1076P50_PR present;
	union SetupRelease_1076P50_u {
		NULL_t	 release;
		SRS_CarrierSwitching_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P50_t;
typedef struct SetupRelease_1076P51 {
	SetupRelease_1076P51_PR present;
	union SetupRelease_1076P51_u {
		NULL_t	 release;
		OverheatingAssistanceConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P51_t;
typedef struct SetupRelease_1076P52 {
	SetupRelease_1076P52_PR present;
	union SetupRelease_1076P52_u {
		NULL_t	 release;
		GapConfig_t	 setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetupRelease_1076P52_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P0;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P0_specs_1;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P0_1[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P1;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P1_specs_4;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P1_4[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P1_constr_4;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P2;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P2_specs_7;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P2_7[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P2_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P3;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P3_specs_10;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P3_10[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P3_constr_10;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P4;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P4_specs_13;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P4_13[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P4_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P5;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P5_specs_16;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P5_16[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P5_constr_16;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P6;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P6_specs_19;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P6_19[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P6_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P7;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P7_specs_22;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P7_22[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P7_constr_22;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P8;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P8_specs_25;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P8_25[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P8_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P9;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P9_specs_28;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P9_28[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P9_constr_28;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P10;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P10_specs_31;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P10_31[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P10_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P11;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P11_specs_34;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P11_34[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P11_constr_34;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P12;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P12_specs_37;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P12_37[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P12_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P13;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P13_specs_40;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P13_40[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P13_constr_40;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P14;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P14_specs_43;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P14_43[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P14_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P15;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P15_specs_46;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P15_46[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P15_constr_46;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P16;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P16_specs_49;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P16_49[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P16_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P17;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P17_specs_52;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P17_52[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P17_constr_52;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P18;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P18_specs_55;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P18_55[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P18_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P19;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P19_specs_58;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P19_58[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P19_constr_58;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P20;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P20_specs_61;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P20_61[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P20_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P21;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P21_specs_64;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P21_64[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P21_constr_64;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P22;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P22_specs_67;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P22_67[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P22_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P23;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P23_specs_70;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P23_70[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P23_constr_70;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P24;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P24_specs_73;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P24_73[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P24_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P25;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P25_specs_76;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P25_76[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P25_constr_76;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P26;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P26_specs_79;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P26_79[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P26_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P27;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P27_specs_82;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P27_82[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P27_constr_82;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P28;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P28_specs_85;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P28_85[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P28_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P29;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P29_specs_88;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P29_88[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P29_constr_88;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P30;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P30_specs_91;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P30_91[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P30_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P31;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P31_specs_94;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P31_94[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P31_constr_94;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P32;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P32_specs_97;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P32_97[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P32_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P33;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P33_specs_100;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P33_100[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P33_constr_100;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P34;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P34_specs_103;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P34_103[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P34_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P35;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P35_specs_106;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P35_106[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P35_constr_106;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P36;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P36_specs_109;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P36_109[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P36_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P37;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P37_specs_112;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P37_112[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P37_constr_112;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P38;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P38_specs_115;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P38_115[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P38_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P39;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P39_specs_118;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P39_118[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P39_constr_118;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P40;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P40_specs_121;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P40_121[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P40_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P41;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P41_specs_124;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P41_124[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P41_constr_124;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P42;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P42_specs_127;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P42_127[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P42_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P43;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P43_specs_130;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P43_130[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P43_constr_130;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P44;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P44_specs_133;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P44_133[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P44_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P45;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P45_specs_136;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P45_136[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P45_constr_136;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P46;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P46_specs_139;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P46_139[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P46_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P47;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P47_specs_142;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P47_142[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P47_constr_142;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P48;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P48_specs_145;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P48_145[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P48_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P49;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P49_specs_148;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P49_148[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P49_constr_148;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P50;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P50_specs_151;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P50_151[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P50_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P51;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P51_specs_154;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P51_154[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P51_constr_154;
extern asn_TYPE_descriptor_t asn_DEF_SetupRelease_1076P52;
extern asn_CHOICE_specifics_t asn_SPC_SetupRelease_1076P52_specs_157;
extern asn_TYPE_member_t asn_MBR_SetupRelease_1076P52_157[2];
extern asn_per_constraints_t asn_PER_type_SetupRelease_1076P52_constr_157;

#ifdef __cplusplus
}
#endif

#endif	/* _SetupRelease_H_ */
#include "asn_internal.h"
