/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6678",
            externalMemoryMap: 
           [          
                ["DDR", 
                     {
                        name: "DDR",
                        base: 0x90000000,                    
                        len: 0x4000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l1DMode: "32k",
          l1PMode: "32k",
          l2Mode: "0k",

    });
    
instance :
    
    override config string codeMemory  = "DDR";   
    override config string dataMemory  = "DDR";                                
    override config string stackMemory = "L2SRAM";

    config String l1DMode = "32k";
    config String l1PMode = "32k";
    config String l2Mode = "0k";
}
